# Generated by Django 5.0.1 on 2024-02-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=50, max_length=50, verbose_name='Название')),
                ('full_text', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
